### ISSUE TITLE
rake install:centos7 fails to upgrade package

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/omnibus-manifold#5]
If we've already installed the package on the Centos VM, the install command will fail:

```
zdavis@gelatinous-cube:~/src/omnibus-manifold$ rake install:centos7
error: Failed dependencies:
	manifold conflicts with manifold-2.0.0~rc.2+git.8.5dc68261-1.el7.x86_64
	manifold is obsoleted by manifold-2.0.0~rc.2+git.8.5dc68261-1.el7.x86_64
	manifold conflicts with (installed) manifold-2.0.0~rc.2-1.el7.x86_64
	manifold is obsoleted by (installed) manifold-2.0.0~rc.2-1.el7.x86_64
Connection to 127.0.0.1 closed.
```
This is happening because that `Platform` class is installing it with the rpm `-i` flag instead of the upgrade `-U` flag. Perhaps we need to add a rake task specifically for upgrading?

Additionally, I noticed that the install command does not maintain the root user's environment. The command is `sudo rpm -ivh #{package_path}` — but when run as the vagrant user, the path won't include manifold-ctl, which could lead to unexpected upgrade results, since the package seems to be detecting it:

```
[vagrant@centos7-install pkg]$ sudo rpm -Uvh manifold-2.0.0~rc.2+git.8.5dc68261-1.el7.x86_64.rpm
Preparing...                          ################################# [100%]
You're about to install manifold!
which: no manifold-ctl in (/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin)
Updating / installing...
   1:manifold-2.0.0~rc.2+git.8.5dc6826^C^C################################# [ 50%]
```

**Comment by scryptmouse** [comment]
RE: rake task, we can actually just swap out the `-i` with `-U`—that upgrades or installs.

Will have a fix for that and the other shortly.
